# Basic Vector input output

In [38]:
pip install altair

Note: you may need to restart the kernel to use updated packages.


In [39]:
import numpy as np
import pandas as pd
import altair as alt

In [40]:
x = np.array([[1],
              [2],
              [3]])

In [41]:
x.shape

(3, 1)

In [42]:
print(f"A 3-dimentional vector:\n {x}")

A 3-dimentional vector:
 [[1]
 [2]
 [3]]


## Vector Addition

In [43]:
x = y = np.array([[1],
                  [2],
                  [3]])

In [44]:
x + y

array([[2],
       [4],
       [6]])

In [45]:
np.add( x, y )

array([[2],
       [4],
       [6]])

## Scalar Multiplication

In [46]:
alpha = 5
x = np.array([[1],
             [2],
             [3]])

In [47]:
alpha * x

array([[ 5],
       [10],
       [15]])

## Linear Combinations

In [48]:
a, b = 2, 3
x , y = np.array([[2],[3]]), np.array([[4], [5]])

In [49]:
a*x + b*y

array([[16],
       [21]])

## Dot product or Inner product

In [50]:
x, y = np.array([[-2],[2]]), np.array([[4],[-3]])

In [51]:
x. T @ y

array([[-14]])

## L2 Norm

In [52]:
x = np.array([[3],[4]])

In [53]:
np.linalg.norm(x, 2)

5.0

## L1 Norm

In [54]:
x = np.array([[3],[-4]])

np.linalg.norm(x, 1)

7.0

## L∞ Norm

In [55]:
x = np.array([[3],[-4]])

np.linalg.norm(x, np.inf)

4.0

## L2 distance between a pair of vectors

In [56]:
distance = np.linalg.norm(x-y, 2)
print(f'L_2 distance : {distance}')

L_2 distance : 1.4142135623730951


## Compute the cosθ between a pair of vectors

In [57]:
x, y = np.array([[1], [2]]), np.array([[5], [7]])

In [58]:
cos_theta = (x.T @ y) / (np.linalg.norm(x,2) * np.linalg.norm(y,2))
print(f'cos of the angle = {np.round(cos_theta, 3)}')

cos of the angle = [[0.988]]


## The exact value of θ we need to take the trigonometric inverse of the cosine function

In [59]:
cos_inverse = np.arccos(cos_theta)
print(f'angle in radiants = {np.round(cos_inverse, 3)}')

angle in radiants = [[0.157]]


In [60]:
degrees = cos_inverse * ((180)/np.pi)
print(f'angle in degrees = {np.round(degrees, 3)}')

angle in degrees = [[8.973]]


## Orthogonal vectors

In [61]:
x = np.array([[2], [0]])
y = np.array([[0], [2]])
cos_theta = (x.T @ y) / (np.linalg.norm(x,2) * np.linalg.norm(y,2))
print(f'cos of the angle = {np.round(cos_theta, 3)}')

cos of the angle = [[0.]]


In [62]:
cos_inverse = np.arccos(cos_theta)
degrees = cos_inverse * ((180)/np.pi)
print(f'angle in radiants = {np.round(cos_inverse, 3)}\nangle in degrees ={np.round(degrees, 3)} ')

angle in radiants = [[1.571]]
angle in degrees =[[90.]] 


## Systems of linear equations

In [63]:
df = pd.DataFrame({"x1": [0, 2], "y1":[8, 3], "x2": [0.5, 2], "y2": [0, 3]})
equation1 = alt.Chart(df).mark_line().encode(x="x1", y="y1")
equation2 = alt.Chart(df).mark_line(color="red").encode(x="x2", y="y2")
equation1 + equation2

alt.LayerChart(...)